name: "These Ricardo"
description: "These Ricardo"

url: "https://poine.github.io/these_ricardo"

#markdown: rdiscount
#markdown: kramdown
#permalink: pretty
#highlighter: pygments
#highlighter: rouge
